language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test application
  - coverage run --source=application manage.py test application
after_success: coveralls