language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py makemigrations application
  - python manage.py migrate application
  - python manage.py test application
  - coverage run --source=home manage.py test application
after_success: coveralls